language: node_js

node_js:
  - '10.1'

sudo: required

cache:
  npm: true
  directories:
  - node_modules

before_script:
  - npm install firebase-tools -g
  - npm install

script:
  - npm test
  - npm run build
  - firebase deploy --only hosting --token "${FIREBASE_TOKEN}"
