language: node_js

node_js:
  - '8.0'

sudo: required

# cache:
#   npm: true
#   directories:
#   - node_modules
#   - functions/node_modules

before_script:
  - ./scripts/dependencies.sh

script:
  - ./scripts/functions.sh
  - ./scripts/hosting.sh
  - ./scripts/deploy.sh
