language: node_js

node_js:
  - '10.1'

sudo: required

cache:
  npm: true
  directories:
  - node_modules
  - functions/node_modules

before_script:
  - ./scripts/dependencies.sh

script:
  - ./scripts/functions.sh
  - ./scripts/hosting.sh
  - ./scripst/deploy.sh
