language: node_js

node_js:
  - '10.1'

sudo: required

cache:
  npm: true
  directories:
  - node_modules
  - functions/node_modules

before_script:
  - npm install -g firebase-tools
  - npm install
  - cd functions
  - npm install

script:
  - npm test
  - cd ..
  - npm test

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
  message: "${TRAVIS_COMMIT_MESSAGE}"
