language: node_js

node_js:
  - '10.1'

sudo: required

cache:
  directories:
  - node_modules

before_script:
  - npm install

script:
  - npm test
  - npm run build
  - firebase deploy --only hosting,functions --token "${FIREBASE_TOKEN}"
